# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.CharField(max_length=1000)),
                ('active_status', models.BooleanField()),
                ('completed_status', models.BooleanField()),
            ],
        ),
    ]
