# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-12 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0014_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoff_list',
            name='checkoff_listID',
        ),
    ]
