# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0017_auto_20170212_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoff_list',
            name='date_time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
