# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0018_auto_20170308_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_report',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
