# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.IntegerField(max_length=30)),
                ('studentID', models.IntegerField()),
                ('iCommonsSA_bool', models.BooleanField()),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('rfid_number', models.IntegerField()),
            ],
        ),
    ]
