# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_checklist_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoff_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkoff_itemID', models.IntegerField()),
                ('date_time_stamp', models.DateTimeField()),
                ('completed_bool', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueID', models.IntegerField()),
                ('roomID', models.IntegerField()),
                ('comment', models.CharField(max_length=10000)),
                ('student_UID', models.IntegerField()),
                ('completed_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='list_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('itemname', models.CharField(max_length=100)),
                ('itemdescription', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.IntegerField()),
                ('building_name', models.CharField(max_length=100)),
                ('floor_number', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('opening_list', models.ManyToManyField(to='data_api.list_items')),
            ],
        ),
        migrations.AddField(
            model_name='checkoff_list',
            name='issueReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Issue_report'),
        ),
        migrations.AddField(
            model_name='checkoff_list',
            name='list_itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.list_items'),
        ),
        migrations.AddField(
            model_name='checkoff_list',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Room'),
        ),
        migrations.AddField(
            model_name='checkoff_list',
            name='studentUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Users'),
        ),
    ]
