# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0005_room_closing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='closing_list',
            field=models.ManyToManyField(related_name='close_list', to='data_api.Checklist_item'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='opening_list',
        ),
        migrations.AddField(
            model_name='room',
            name='opening_list',
            field=models.ManyToManyField(related_name='open_list', to='data_api.Checklist_item'),
        ),
    ]
