# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0006_auto_20161112_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoff_list',
            name='studentUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Users', verbose_name='student uid'),
        ),
        migrations.AlterField(
            model_name='users',
            name='studentID',
            field=models.IntegerField(verbose_name='student uid'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uniqueID',
            field=models.IntegerField(),
        ),
    ]
