# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0010_auto_20161124_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_item',
            name='completed_status',
        ),
    ]
