# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0011_remove_checklist_item_completed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_report',
            name='comment',
            field=models.CharField(max_length=140),
        ),
    ]
