# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0012_auto_20161125_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_report',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Room', verbose_name='roomid'),
        ),
        migrations.AlterField(
            model_name='issue_report',
            name='student_UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.User', verbose_name='student uid'),
        ),
    ]
