# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0013_auto_20161125_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Admin',
            field=models.BooleanField(default=False),
        ),
    ]
